"use client";
import "./globals.css";
import Link from "next/link";
import { ErrorWrapper } from "./error-wrapper";
import { useState } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-300 p-4 text-center">
          <h1 className="text-xl md:text-2xl font-bold">My App</h1>
        </header>

        {/* Desktop Navigation */}
        <nav className="hidden md:flex justify-around bg-gray-300 p-4 mt-4">
          <Link href="/" className="hover:text-blue-500 transition px-2">
            Home
          </Link>
          <Link
            href="/products"
            className="hover:text-blue-500 transition px-2"
          >
            Products
          </Link>
          <Link href="/blog" className="hover:text-blue-500 transition px-2">
            Blog
          </Link>
          <Link
            href="/complex-dashboard"
            className="hover:text-blue-500 transition px-2"
          >
            Complex Dashboard
          </Link>
        </nav>

        {/* Mobile Navigation */}
        <nav>
          <button
            onClick={() => setIsMenuOpen(!isMenuOpen)}
            className="text-2xl font-bold m-4 p-2 bg-blue-300 rounded-md md:hidden"
          >
            ☰
          </button>
          {isMenuOpen && (
            <div className="flex flex-col gap-3 mt-4 p-4 bg-amber-100 md:hidden">
              <Link
                href="/"
                className="hover:text-blue-500 text-rose-600 block py-2 transition"
              >
                Home
              </Link>
              <Link
                href="/products"
                className="hover:text-blue-500 text-rose-600 block py-2 transition"
              >
                Products
              </Link>
              <Link
                href="/blog"
                className="hover:text-blue-500 text-rose-600 block py-2 transition"
              >
                Blog
              </Link>
              <Link
                href="/complex-dashboard"
                className="hover:text-blue-500 text-rose-600 block py-2 transition"
              >
                Complex Dashboard
              </Link>
            </div>
          )}
        </nav>

        <ErrorWrapper>{children}</ErrorWrapper>
        <footer className="bg-rose-300 p-4 text-center text-sm md:text-base">
          <p>© 2025 My App. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
