import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-300 p-4 text-center">Header</header>
        <nav className="flex justify-around bg-gray-300 p-4 mt-4">
          <Link href="/" className="hover:text-blue-500">
            Home
          </Link>
          <Link href="/products" className="hover:text-blue-500">
            Products
          </Link>
          <Link href="/blog" className="hover:text-blue-500">
            Blog
          </Link>
        </nav>
        {children}
        <footer className="bg-pink-300 p-4 text-center">Footer</footer>
      </body>
    </html>
  );
}
