import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
        style={{
            backgroundColor: "lightblue",
            padding: "1rem",
            textAlign: "center",
        }}
        >Header</header>
        <nav style={{
          display: "flex",
          justifyContent: "space-around",
          backgroundColor: "#aaa",
          padding: "1rem",
          marginTop: "1rem",
        }}>
          <Link href="/">Home</Link>
          <Link href="/products">Products</Link>
        </nav>
        {children}
        <footer
        style={{
            backgroundColor: "pink",
            padding: "1rem",
            textAlign: "center",
        }}
        >Footer</footer>
      </body>
    </html>
  )
}
